/**
 * Starter kits: an industry's pipeline, appointment types, intake form and
 * automations installed in one click. Everything a kit creates is an ordinary
 * record the company can edit or delete. Installing twice adds nothing twice.
 */
import { coreDb } from "@/lib/core/db";
import type { Step, Trigger } from "@/lib/automations/engine";

type Kit = {
  key: string; name: string; for: string; blurb: string;
  pipeline: { name: string; stages: [string, string, number, number, number][] };
  eventTypes: { name: string; slug: string; minutes: number; description: string; modes: string[] }[];
  forms: { title: string; description: string; fields: { id: string; label: string; type: string; required: boolean; options: string[] }[] }[];
  workflows: { name: string; description: string; trigger: Trigger; exitTrigger?: Trigger; steps: Step[] }[];
};

export const KITS: Kit[] = [
  { key: "field_service", name: "Field service", for: "HVAC, plumbing, electrical, cleaning, landscaping", blurb: "Estimate-to-job pipeline, estimate and service visits, a service request form, and automations that confirm, remind, follow up and ask for reviews.",
    pipeline: { name: "Service pipeline", stages: [["NEW REQUEST", "#6B7280", 10, 0, 0], ["ESTIMATE SCHEDULED", "#8B5CF6", 30, 0, 0], ["ESTIMATE SENT", "#3B82F6", 50, 0, 0], ["APPROVED", "#F59E0B", 80, 0, 0], ["JOB SCHEDULED", "#F97316", 90, 0, 0], ["CLOSED WON", "#10B981", 100, 1, 0], ["CLOSED LOST", "#374151", 0, 0, 1]] },
    eventTypes: [{ name: "Free estimate", slug: "free-estimate", minutes: 45, description: "We come out, look at the job and give you a written price on the spot.", modes: ["IN_PERSON"] }, { name: "Service visit", slug: "service-visit", minutes: 90, description: "Scheduled service at your address.", modes: ["IN_PERSON"] }, { name: "Phone consult", slug: "phone-consult", minutes: 15, description: "Quick call to scope the work.", modes: ["PHONE"] }],
    forms: [{ title: "Service request", description: "Tell us what's going on and we'll get back within the hour.", fields: [{ id: "address", label: "Service address", type: "SHORT", required: true, options: [] }, { id: "issue", label: "What do you need help with?", type: "LONG", required: true, options: [] }, { id: "urgency", label: "How urgent is it?", type: "SELECT", required: true, options: ["Emergency (today)", "This week", "Flexible"] }, { id: "photos", label: "Photos (optional)", type: "FILE", required: false, options: [] }] }],
    workflows: [
      { name: "New request: fast response", description: "Thank them, alert the team, task due now.", trigger: "FORM_SUBMITTED", steps: [{ type: "NOTIFY_TEAM", message: "New service request from {{contact.name}} ({{contact.phone}})" }, { type: "SEND_SMS", body: "Hi {{contact.first_name}}, {{company.name}} here. Got your request. We'll call you within the hour." }, { type: "CREATE_TASK", title: "Call {{contact.name}} about their request", dueInDays: 0, priority: "HIGH" }] as Step[] },
      { name: "Job booked: confirm + reminder", description: "Confirmation text now, reminder the day before.", trigger: "JOB_CREATED", steps: [{ type: "SEND_SMS", body: "You're booked with {{company.name}}. We'll text when the tech is on the way." }, { type: "WAIT", amount: 1, unit: "days" }, { type: "SEND_SMS", body: "Reminder: {{company.name}} is scheduled for your service. Reply if anything changed." }] as Step[] },
      { name: "Job done: review request", description: "Thank-you text, review ask two days later.", trigger: "JOB_COMPLETED", steps: [{ type: "SEND_SMS", body: "Thanks for choosing {{company.name}}! If anything isn't right, reply here and we'll fix it." }, { type: "WAIT", amount: 2, unit: "days" }, { type: "SEND_EMAIL", subject: "How did we do?", body: "Hi {{contact.first_name}},\n\nThanks again for having {{company.name}} out. A quick review helps our small team a lot: {{company.website}}\n\nThank you!" }] as Step[] },
      { name: "Estimate sent: 3-day chase", description: "Follow up until they decide. Exits when the deal moves.", trigger: "DEAL_STAGE_CHANGED", exitTrigger: "DEAL_WON", steps: [{ type: "WAIT", amount: 3, unit: "days" }, { type: "SEND_SMS", body: "Hi {{contact.first_name}}, any questions on the estimate from {{company.name}}? Happy to walk through it." }, { type: "WAIT", amount: 4, unit: "days" }, { type: "CREATE_TASK", title: "Call {{contact.name}} about the open estimate", dueInDays: 0, priority: "MEDIUM" }] as Step[] },
    ] },
  { key: "dealership", name: "Dealership", for: "Car, truck, RV and powersports dealers", blurb: "Lead-to-delivery pipeline, test drive and finance appointments, a vehicle inquiry form, and automations for leads, lender submissions, contracts and delivery follow-up.",
    pipeline: { name: "Sales pipeline", stages: [["NEW LEAD", "#6B7280", 10, 0, 0], ["CONTACTED", "#8B5CF6", 25, 0, 0], ["APPOINTMENT SET", "#3B82F6", 40, 0, 0], ["TEST DRIVE", "#F59E0B", 60, 0, 0], ["IN FINANCE", "#F97316", 80, 0, 0], ["CLOSED WON", "#10B981", 100, 1, 0], ["CLOSED LOST", "#374151", 0, 0, 1]] },
    eventTypes: [{ name: "Test drive", slug: "test-drive", minutes: 45, description: "Pick a time and we'll have the vehicle ready out front.", modes: ["IN_PERSON"] }, { name: "Finance appointment", slug: "finance-appointment", minutes: 60, description: "Go over numbers and paperwork with our finance manager.", modes: ["IN_PERSON", "PHONE"] }, { name: "Service appointment", slug: "service-appointment", minutes: 60, description: "Book your service visit.", modes: ["IN_PERSON"] }],
    forms: [{ title: "Vehicle inquiry", description: "Tell us what you're looking for.", fields: [{ id: "vehicle", label: "Vehicle you're interested in", type: "SHORT", required: true, options: [] }, { id: "trade", label: "Do you have a trade-in?", type: "SELECT", required: true, options: ["Yes", "No"] }, { id: "budget", label: "Monthly budget", type: "SELECT", required: false, options: ["Under $300", "$300–$500", "$500–$800", "$800+"] }, { id: "timing", label: "When are you looking to buy?", type: "SELECT", required: true, options: ["This week", "This month", "Just browsing"] }] }],
    workflows: [
      { name: "Internet lead: 10-minute response", description: "Alert sales, text the lead, task now.", trigger: "FORM_SUBMITTED", steps: [{ type: "NOTIFY_TEAM", message: "New vehicle inquiry from {{contact.name}} ({{contact.phone}})" }, { type: "SEND_SMS", body: "Hi {{contact.first_name}}, thanks for reaching out to {{company.name}}. Is the vehicle still what you're after? Want to set up a test drive?" }, { type: "CREATE_TASK", title: "Call {{contact.name}} (internet lead)", dueInDays: 0, priority: "URGENT" }] as Step[] },
      { name: "Deal submitted to lenders: keep them warm", description: "Set expectations while finance works.", trigger: "VEHICLE_DEAL_SUBMITTED", steps: [{ type: "SEND_SMS", body: "{{contact.first_name}}, your application is with our lenders. We'll text as soon as we have an answer, usually within the hour." }] as Step[] },
      { name: "Contract sent: nudge to sign", description: "Reminder if the contract sits.", trigger: "VEHICLE_CONTRACT_SENT", steps: [{ type: "WAIT", amount: 1, unit: "days" }, { type: "SEND_SMS", body: "Hi {{contact.first_name}}, your paperwork from {{company.name}} is ready to sign. Reply with any questions." }] as Step[] },
      { name: "Delivered: thank you + review", description: "Thank you, then review ask, then first-service reminder.", trigger: "DEAL_WON", steps: [{ type: "SEND_SMS", body: "Congrats on the new ride, {{contact.first_name}}! Thanks for choosing {{company.name}}." }, { type: "WAIT", amount: 3, unit: "days" }, { type: "SEND_EMAIL", subject: "How's the new vehicle?", body: "Hi {{contact.first_name}},\n\nWe hope you're loving it. If you have a minute, a review helps us a lot: {{company.website}}\n\n{{company.name}}" }] as Step[] },
    ] },
  { key: "credit_repair", name: "Credit repair", for: "Credit repair and dispute firms", blurb: "Consult-to-client pipeline, consult and review calls, an intake form, and automations around enrollment and each dispute round.",
    pipeline: { name: "Client pipeline", stages: [["NEW LEAD", "#6B7280", 10, 0, 0], ["CONSULT BOOKED", "#8B5CF6", 30, 0, 0], ["REPORTS RECEIVED", "#3B82F6", 50, 0, 0], ["AGREEMENT SENT", "#F59E0B", 70, 0, 0], ["CLOSED WON", "#10B981", 100, 1, 0], ["CLOSED LOST", "#374151", 0, 0, 1]] },
    eventTypes: [{ name: "Free credit consult", slug: "credit-consult", minutes: 30, description: "We review your situation and explain exactly what we can dispute.", modes: ["PHONE", "VIDEO"] }, { name: "Monthly review call", slug: "monthly-review", minutes: 20, description: "Progress on your disputes and next steps.", modes: ["PHONE"] }],
    forms: [{ title: "Credit consultation intake", description: "A few questions so we can prepare for your consult.", fields: [{ id: "goal", label: "What's your main goal?", type: "SELECT", required: true, options: ["Buy a home", "Buy a car", "Lower interest rates", "Remove errors"] }, { id: "score", label: "Approximate current score", type: "NUMBER", required: false, options: [] }, { id: "items", label: "Anything specific you want removed?", type: "LONG", required: false, options: [] }] }],
    workflows: [
      { name: "New lead: consult nudge", description: "Thank them and push to book.", trigger: "FORM_SUBMITTED", exitTrigger: "BOOKING_CREATED", steps: [{ type: "SEND_SMS", body: "Hi {{contact.first_name}}, {{company.name}} here. Thanks for reaching out. Grab a free consult time: {{company.website}}" }, { type: "WAIT", amount: 2, unit: "days" }, { type: "SEND_EMAIL", subject: "Still want help with your credit?", body: "Hi {{contact.first_name}},\n\nOur consult is free and takes 30 minutes. Pick a time that works: {{company.website}}\n\n{{company.name}}" }] as Step[] },
      { name: "Dispute round opened: client update", description: "Tell the client what was sent and when to expect results.", trigger: "DISPUTE_ROUND_OPENED", steps: [{ type: "SEND_EMAIL", subject: "Your dispute round is in", body: "Hi {{contact.first_name}},\n\nWe've sent your next round of disputes. Bureaus have 30 days to respond. We'll update you the moment we hear back.\n\n{{company.name}}" }, { type: "WAIT", amount: 30, unit: "days" }, { type: "CREATE_TASK", title: "Check bureau responses for {{contact.name}}", dueInDays: 0, priority: "HIGH" }] as Step[] },
      { name: "Dispute round closed: results + review", description: "Share results and ask for a review.", trigger: "DISPUTE_ROUND_CLOSED", steps: [{ type: "SEND_SMS", body: "{{contact.first_name}}, your dispute round is closed. Check your portal for results, and let us know if you have questions." }, { type: "WAIT", amount: 2, unit: "days" }, { type: "SEND_EMAIL", subject: "A quick favor", body: "Hi {{contact.first_name}},\n\nIf we've helped, a short review means a lot to a small team: {{company.website}}\n\nThank you,\n{{company.name}}" }] as Step[] },
    ] },
  { key: "marketing_agency", name: "Marketing agency", for: "Agencies, consultants, web and automation studios", blurb: "Discovery-to-retainer pipeline, discovery and kickoff calls, a project brief form, and automations for leads, proposals and onboarding.",
    pipeline: { name: "Agency pipeline", stages: [["NEW LEAD", "#6B7280", 10, 0, 0], ["DISCOVERY BOOKED", "#8B5CF6", 25, 0, 0], ["PROPOSAL SENT", "#3B82F6", 50, 0, 0], ["NEGOTIATION", "#F59E0B", 75, 0, 0], ["CLOSED WON", "#10B981", 100, 1, 0], ["CLOSED LOST", "#374151", 0, 0, 1]] },
    eventTypes: [{ name: "Discovery call", slug: "discovery-call", minutes: 30, description: "Tell us about your business and what you're trying to grow.", modes: ["VIDEO", "PHONE"] }, { name: "Project kickoff", slug: "project-kickoff", minutes: 60, description: "Goals, timeline, access and first milestones.", modes: ["VIDEO"] }],
    forms: [{ title: "Project brief", description: "Help us prepare for your discovery call.", fields: [{ id: "business", label: "Your business and website", type: "SHORT", required: true, options: [] }, { id: "goal", label: "What would a win look like in 90 days?", type: "LONG", required: true, options: [] }, { id: "budget", label: "Monthly budget", type: "SELECT", required: true, options: ["Under $1,000", "$1,000–$3,000", "$3,000–$10,000", "$10,000+"] }] }],
    workflows: [
      { name: "Lead: book discovery", description: "Push every lead toward a discovery call. Exits once booked.", trigger: "CONTACT_CREATED", exitTrigger: "BOOKING_CREATED", steps: [{ type: "SEND_EMAIL", subject: "Thanks, {{contact.first_name}}", body: "Hi {{contact.first_name}},\n\nThanks for reaching out to {{company.name}}. The fastest next step is a 30-minute discovery call: {{company.website}}\n\nTalk soon." }, { type: "WAIT", amount: 2, unit: "days" }, { type: "SEND_SMS", body: "Hi {{contact.first_name}}, {{company.name}} here. Want to grab a discovery slot this week?" }, { type: "WAIT", amount: 3, unit: "days" }, { type: "CREATE_TASK", title: "Call {{contact.name}} (no discovery booked)", dueInDays: 0, priority: "MEDIUM" }] as Step[] },
      { name: "Proposal sent: follow-up", description: "Chase the proposal until they decide.", trigger: "DEAL_STAGE_CHANGED", exitTrigger: "DEAL_WON", steps: [{ type: "WAIT", amount: 2, unit: "days" }, { type: "SEND_EMAIL", subject: "Questions on the proposal?", body: "Hi {{contact.first_name}},\n\nJust checking in on the proposal. Happy to adjust scope or walk through it on a call.\n\n{{company.name}}" }, { type: "WAIT", amount: 5, unit: "days" }, { type: "CREATE_TASK", title: "Call {{contact.name}} about the proposal", dueInDays: 0, priority: "HIGH" }] as Step[] },
      { name: "Won: onboarding", description: "Welcome, kickoff booking, first-week check-in.", trigger: "DEAL_WON", steps: [{ type: "SEND_EMAIL", subject: "Welcome aboard", body: "Hi {{contact.first_name}},\n\nWe're excited to get started. Book your kickoff here: {{company.website}}\n\n{{company.name}}" }, { type: "ADD_TAG", tag: "client" }, { type: "WAIT", amount: 7, unit: "days" }, { type: "CREATE_TASK", title: "Week-one check-in with {{contact.name}}", dueInDays: 0, priority: "MEDIUM" }] as Step[] },
    ] },
];

export async function installKit(tenantId: string, key: string, by: string): Promise<Record<string, number>> {
  const kit = KITS.find((k) => k.key === key); if (!kit) throw new Error("Unknown starter kit.");
  const db = coreDb(); const now = new Date().toISOString(); const n: Record<string, number> = { pipelines: 0, stages: 0, eventTypes: 0, forms: 0, workflows: 0 };
  if (!(await db.prepare("SELECT id FROM crm_pipelines WHERE tenant_id=? AND name=?").bind(tenantId, kit.pipeline.name).first())) {
    const pid = crypto.randomUUID(); const isFirst = !(await db.prepare("SELECT id FROM crm_pipelines WHERE tenant_id=? AND active=1").bind(tenantId).first());
    await db.prepare("INSERT INTO crm_pipelines (id, name, description, is_default, active, tenant_id, created_at, updated_at) VALUES (?,?,?,?,1,?,?,?)").bind(pid, kit.pipeline.name, `${kit.name} starter kit`, isFirst ? 1 : 0, tenantId, now, now).run(); n.pipelines++;
    for (const [i, st] of kit.pipeline.stages.entries()) { await db.prepare("INSERT INTO crm_pipeline_stages (id, pipeline_id, name, color, position, probability, is_won, is_lost, tenant_id, created_at, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(), pid, st[0], st[1], i, st[2], st[3], st[4], tenantId, now, now).run(); n.stages++; }
  }
  for (const et of kit.eventTypes) {
    if (await db.prepare("SELECT id FROM calendar_event_types WHERE tenant_id=? AND lower(name)=lower(?)").bind(tenantId, et.name).first()) continue;
    let slug = et.slug; let k = 0; while (await db.prepare("SELECT id FROM calendar_event_types WHERE slug=?").bind(slug).first()) slug = `${et.slug}-${++k}`;
    await db.prepare("INSERT INTO calendar_event_types (id, name, slug, description, duration_minutes, duration_options, buffer_before_minutes, buffer_after_minutes, capacity, location_modes, video_platforms, tenant_id, created_at, updated_at) VALUES (?,?,?,?,?,?,0,0,1,?,?,?,?,?)")
      .bind(crypto.randomUUID(), et.name, slug, et.description, et.minutes, JSON.stringify([et.minutes]), JSON.stringify(et.modes), JSON.stringify(["GOOGLE_MEET", "ZOOM"]), tenantId, now, now).run(); n.eventTypes++;
  }
  for (const f of kit.forms) {
    if (await db.prepare("SELECT id FROM crm_forms WHERE tenant_id=? AND title=?").bind(tenantId, f.title).first()) continue;
    const token = crypto.randomUUID().replaceAll("-", "");
    await db.prepare("INSERT INTO crm_forms (id,title,description,status,public_token,fields_json,requires_signature,created_by,tenant_id,settings_json,created_at,updated_at) VALUES (?,?,?,'PUBLISHED',?,?,0,?,?,?,?,?)")
      .bind(crypto.randomUUID(), f.title, f.description, token, JSON.stringify(f.fields), by, tenantId, JSON.stringify({ afterSubmit: "message", successMessage: "Thanks, we'll be in touch shortly.", tags: "", assignTo: "", bookingEvent: "" }), now, now).run(); n.forms++;
  }
  for (const w of kit.workflows) {
    if (await db.prepare("SELECT id FROM automation_workflows WHERE tenant_id=? AND name=?").bind(tenantId, w.name).first()) continue;
    await db.prepare("INSERT INTO automation_workflows (id,tenant_id,name,description,trigger,trigger_filter,steps,active,exit_trigger,settings_json,created_by,created_at,updated_at) VALUES (?,?,?,?,?,'{}',?,1,?,'{}',?,?,?)")
      .bind(crypto.randomUUID(), tenantId, w.name, w.description, w.trigger, JSON.stringify(w.steps), w.exitTrigger || null, by, now, now).run(); n.workflows++;
  }
  return n;
}
