import { chromium } from "playwright-core";
const BASE="http://127.0.0.1:5177"; const stamp=Date.now();
async function api(p,init={},cookie=""){const r=await fetch(BASE+p,{...init,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})}});let b=null;try{b=await r.json()}catch{}return{r,b,cookie:(r.headers.get("set-cookie")||"").split(";")[0]}}
const s=await api("/api/tenants/signup",{method:"POST",body:JSON.stringify({tenantName:`Btn ${stamp}`,displayName:"Btn",email:`btn+${stamp}@example.com`,password:"Password123!"})});
const c=s.cookie; const et=await api("/api/calendar/event-types",{method:"POST",body:JSON.stringify({name:"Consult",slug:`consult-${stamp}`,durationMinutes:30})},c);
const st=new Date();st.setHours(14,0,0,0);await api("/api/calendar/bookings",{method:"POST",body:JSON.stringify({eventTypeId:et.b?.id,customerName:"Test Person",customerEmail:`tp+${stamp}@example.com`,startsAt:st.toISOString(),timezone:"America/Chicago",locationMode:"VIDEO",videoPlatform:"GOOGLE_MEET"})},c);
const browser=await chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",headless:true,args:["--no-sandbox"]});
const ctx=await browser.newContext({viewport:{width:1500,height:950}});
await ctx.addCookies([{name:"cyncro_session",value:c.split("=")[1],domain:"127.0.0.1",path:"/"}]);
const page=await ctx.newPage(); const errors=[];
page.on("pageerror",e=>errors.push("pageerror: "+e.message)); page.on("console",m=>{if(m.type()==="error")errors.push("console: "+m.text().slice(0,160))});
page.on("dialog",d=>{console.log("dialog:",d.type(),d.message().slice(0,60));d.dismiss()});
await page.goto(`${BASE}/#admin`,{waitUntil:"networkidle"}); await page.waitForTimeout(2500);
const bar=page.locator(".calendarCommandBar");
const results=[];
const tryClick=async(label,loc,check)=>{try{await loc.first().click({timeout:3000});await page.waitForTimeout(500);const ok=await check();results.push(`${ok?"PASS":"FAIL"} ${label}`)}catch(e){results.push(`FAIL ${label} · ${String(e.message).split("\n")[0].slice(0,90)}`)}};
await tryClick("Month view",bar.getByRole("button",{name:/^Month$/}),async()=>await page.locator(".roleCalendar.month").count()>0);
await tryClick("Week view",bar.getByRole("button",{name:/^Week$/}),async()=>await page.locator(".roleCalendar.week").count()>0);
await tryClick("List view",bar.getByRole("button",{name:/^List$/}),async()=>await page.locator(".roleCalendar").count()===0);
await tryClick("Slots view",bar.getByRole("button",{name:/Slots/}),async()=>await page.locator(".calendarSlotsView").count()>0);
await tryClick("Revenue view",bar.getByRole("button",{name:/Revenue/}),async()=>await page.locator(".revenueCalendar").count()>0);
await tryClick("Team view",bar.getByRole("button",{name:/Team/}),async()=>await page.locator(".teamCalendar").count()>0);
await tryClick("Waitlist view",bar.getByRole("button",{name:/Waitlist/}),async()=>(await page.locator("text=/waitlist/i").count())>0);
await tryClick("Back to Week",bar.getByRole("button",{name:/^Week$/}),async()=>await page.locator(".roleCalendar.week").count()>0);
const headBefore=await page.locator(".roleCalendarHead b").innerText();
await tryClick("Next ›",bar.getByRole("button",{name:/Next/}),async()=>(await page.locator(".roleCalendarHead b").innerText())!==headBefore);
await tryClick("‹ Prev",bar.getByRole("button",{name:/Prev/}),async()=>(await page.locator(".roleCalendarHead b").innerText())===headBefore);
await tryClick("Today",bar.getByRole("button",{name:/^Today$/}),async()=>true);
await tryClick("Block time",bar.getByRole("button",{name:/Block time/}),async()=>(await page.locator("text=/block/i").count())>1);
await page.locator(".modalback").first().click({position:{x:5,y:5}}).catch(()=>{});await page.waitForTimeout(300);
await tryClick("Event types",bar.getByRole("button",{name:/Event types/}),async()=>(await page.locator("text=/event type/i").count())>1);
await page.locator(".modalback").first().click({position:{x:5,y:5}}).catch(()=>{});await page.waitForTimeout(300);
await tryClick("Resources",bar.getByRole("button",{name:/^◈ Resources$/}),async()=>(await page.locator("text=/resource/i").count())>1);
await page.locator(".modalback").first().click({position:{x:5,y:5}}).catch(()=>{});await page.waitForTimeout(300);
await tryClick("Book appointment",bar.getByRole("button",{name:/Book appointment/}),async()=>(await page.locator("text=/customer/i").count())>0);
await page.locator(".modalback").first().click({position:{x:5,y:5}}).catch(()=>{});await page.waitForTimeout(300);
await tryClick("Appointment •••",page.locator(".table .tr button").first(),async()=>(await page.locator("text=/reschedule|cancel/i").count())>0);
await page.locator(".modalback").first().click({position:{x:5,y:5}}).catch(()=>{});await page.waitForTimeout(300);
await tryClick("Refresh",page.locator(".table .crmPanelHead button"),async()=>true);
await tryClick("Strip: day click",page.locator(".calCCMonth button.today"),async()=>await page.locator(".roleCalendar.week").count()>0);
await tryClick("Strip: booking block",page.locator(".calCCBlock").first(),async()=>(await page.locator("text=/reschedule|cancel/i").count())>0);
await page.locator(".modalback").first().click({position:{x:5,y:5}}).catch(()=>{});await page.waitForTimeout(300);
await tryClick("Strip: copy link",page.locator(".calCCLinks > button").first(),async()=>(await page.locator(".calCCLinks em").first().innerText()).includes("Copied"));
await tryClick("Connect Google",page.locator(".externalCalendarBar button").first(),async()=>true);
console.log(results.join("\n")); console.log("errors:",errors.length?errors.slice(0,6):"none"); await page.screenshot({path:process.env.OUT+"/btn-end.png"});
// back-button behaviour
await page.goto(`${BASE}/#home`,{waitUntil:"networkidle"});await page.waitForTimeout(800);
await page.click("text=Calendar");await page.waitForTimeout(800);console.log("after Calendar click:",page.url());
await page.click("text=Cyncro CRM");await page.waitForTimeout(800);console.log("after CRM click:",page.url());
await page.goBack();await page.waitForTimeout(800);console.log("after back #1:",page.url(),"visible strip?",await page.locator(".calCC").count());
await page.goBack();await page.waitForTimeout(800);console.log("after back #2:",page.url());
await browser.close();
