/**
 * Real AI-drafted outreach email for a prospect — grounded in the real
 * signals and sales brief already generated by /api/prospecting/analyze
 * (pitch angle, why-call, what-was-found), never a generic template.
 * Same Anthropic call pattern as app/api/studio/ai-rewrite/route.ts.
 */
import { ensureCoreSchema } from "@/lib/core/db";
import { requireTenant } from "@/lib/core/tenantAuth";
import { env } from "cloudflare:workers";
type CfEnv = Record<string, string | undefined>;

export async function POST(request: Request) {
  try {
    await ensureCoreSchema();
    const tenant = await requireTenant(request);
    if (tenant instanceof Response) return tenant;
    const body = (await request.json()) as {
      businessName?: string; category?: string; whyCall?: string; whatFound?: string;
      recommendedSolution?: string; pitchAngle?: string;
    };
    const businessName = String(body.businessName || "").trim().slice(0, 200);
    if (!businessName) return Response.json({ error: "businessName is required." }, { status: 400 });

    const cfEnv = env as CfEnv;
    const apiKey = cfEnv.ANTHROPIC_API_KEY || process.env.ANTHROPIC_API_KEY;
    if (!apiKey) return Response.json({ error: "AI outreach drafting isn't configured (missing API key)." }, { status: 503 });

    const brief = [
      `Business: ${businessName}${body.category ? ` (${body.category})` : ""}`,
      body.whatFound ? `What we found: ${body.whatFound}` : null,
      body.whyCall ? `Why this is a fit: ${body.whyCall}` : null,
      body.recommendedSolution ? `Recommended angle: ${body.recommendedSolution}` : null,
      body.pitchAngle ? `Best pitch angle: ${body.pitchAngle}` : null,
    ].filter(Boolean).join("\n");
    if (brief.split("\n").length < 2) return Response.json({ error: "Run analysis on this prospect first so there's real detail to draft from." }, { status: 400 });

    const prompt = `You are a sales rep writing a first-touch cold outreach email. Use only the real facts below — never invent details about the business.

${brief}

Write a short (under 100 words), specific, non-generic cold email referencing the actual finding above. No subject line, just the email body. Sign off as "the team" (no invented sender name).`;

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model: "claude-haiku-4-5-20251001", max_tokens: 400, messages: [{ role: "user", content: prompt }] }),
    });
    if (!response.ok) {
      const detail = await response.text().catch(() => "");
      return Response.json({ error: `AI request failed (${response.status})${detail ? `: ${detail.slice(0, 200)}` : ""}` }, { status: 502 });
    }
    type AnthropicResponse = { content?: Array<{ type: string; text?: string }> };
    const data = (await response.json()) as AnthropicResponse;
    const text = data.content?.find((b) => b.type === "text")?.text?.trim() || "";
    if (!text) return Response.json({ error: "AI returned an empty response." }, { status: 502 });
    return Response.json({ email: text });
  } catch (error) {
    console.error("prospecting.outreach_failed", error);
    return Response.json({ error: "Unable to draft outreach email." }, { status: 500 });
  }
}
