"use client";
import { useState } from "react";

const times=["9:00 AM","9:30 AM","10:30 AM","1:00 PM","2:30 PM","4:00 PM"];
export default function Home(){
 const [tab,setTab]=useState("book"),[step,setStep]=useState(1),[location,setLocation]=useState(""),[time,setTime]=useState(""),[view,setView]=useState("Month");
 return <main><header><div className="logo"><i>Cyncro</i> Core</div><nav><button onClick={()=>setTab("book")}>Customer booking</button><button onClick={()=>setTab("admin")}>Admin calendar</button><span>● DEMO LIVE</span></nav></header>
 {tab==="admin"?<Admin onCreate={()=>setTab("book")}/>:<section className="wrap"><p className="eyebrow">CYNCRO MEDIA • PRIVATE BOOKING</p><div className="card"><aside><div className="mark">C</div><small>Cyncro Media</small><h1>Executive<br/>Strategy Session</h1><p>A focused private session to map your goals, systems, and next move.</p><hr/><b>◷ 30 minutes</b><small>Eastern Time</small><hr/><b>✦ Instant confirmation</b><small>Email details included</small><footer>◆ Conflict-protected scheduling</footer></aside><article>
 <div className="progress"><b>{step}</b> of 3</div>
 {step===1&&<><label>STEP 1 OF 3</label><h2>How would you like to meet?</h2><p>Choose the setting that works best for you.</p><div className="locations">{[["Video call","Meet, Zoom, or FaceTime"],["Phone call","We’ll call your number"],["In person","Confirm the meeting address"]].map(x=><button onClick={()=>{setLocation(x[0]);setStep(2)}} key={x[0]}><i>◇</i><b>{x[0]}</b><small>{x[1]}</small><em>→</em></button>)}</div><div className="note"><b>Your time is protected.</b> Availability updates in real time with automatic double-booking protection.</div></>}
 {step===2&&<><div className="row"><div><label>STEP 2 OF 3</label><h2>Select a date & time</h2></div><div className="toggle">{["Month","Week"].map(x=><button className={view===x?"on":""} onClick={()=>setView(x)} key={x}>{x}</button>)}</div></div><div className="calendar"><div><h3>‹　 August 2026　 ›</h3><div className="days">{"SMTWTFS".split("").map((x,i)=><small key={i}>{x}</small>)}{Array.from({length:31},(_,i)=><button className={i+1===18?"selected":""} key={i}>{i+1}</button>)}</div></div><div className="times"><b>Tuesday, August 18</b>{times.map(x=><button className={time===x?"selected":""} onClick={()=>setTime(x)} key={x}>{x}</button>)}</div></div><div className="actions"><button onClick={()=>setStep(1)}>Back</button><button disabled={!time} onClick={()=>setStep(3)}>Continue →</button></div></>}
 {step===3&&<><label>STEP 3 OF 3</label><h2>Complete your booking</h2><div className="held">Held for you • 04:58</div><div className="summary">Tuesday, August 18 at {time}<small>30 min · {location}</small></div><div className="form"><input placeholder="First name"/><input placeholder="Last name"/><input placeholder="Email address"/><input placeholder="Phone number"/>{location==="Video call"&&<select><option>Google Meet</option><option>Zoom</option><option>Apple FaceTime</option></select>}{location==="In person"&&<input placeholder="Meeting address"/>}</div><div className="actions"><button onClick={()=>setStep(2)}>Back</button><button onClick={()=>setStep(4)}>Confirm booking →</button></div></>}
 {step===4&&<div className="success"><div>✓</div><label>BOOKING CONFIRMED</label><h2>You’re officially on the calendar.</h2><p>Tuesday, August 18 at {time} · {location}</p><div className="note">A full confirmation with meeting details has been sent to your email.</div><button onClick={()=>{setStep(1);setTime("")}}>Book another session</button></div>}
 </article></div></section>}</main>}

function Admin({onCreate}:{onCreate:()=>void}){const rows=[["Aug 18 · 9:00 AM","Avery Morgan","Executive Strategy","Google Meet","Confirmed"],["Aug 18 · 11:30 AM","Jordan Blake","Private Consultation","In person","Confirmed"],["Aug 19 · 1:00 PM","Taylor Brooks","Executive Strategy","Phone","Pending"],["Aug 21 · 3:30 PM","Morgan Reed","Systems Intensive","Zoom","Confirmed"]];return <section className="admin"><div className="adminhead"><div><label>UNIVERSAL CALENDAR</label><h1>Booking management</h1><p>Availability, resources, contacts, and scheduling controls in one place.</p></div><button onClick={onCreate}>+ Create booking</button></div><div className="stats">{[["BOOKINGS THIS WEEK","24"],["CONFIRMATION RATE","96%"],["HOST UTILIZATION","78%"],["WAITLIST","6"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><p>Live backend status</p></div>)}</div><div className="table"><h3>Upcoming bookings</h3>{rows.map((r,i)=><div className="tr" key={i}>{r.map((x,j)=><span key={j}><b>{x}</b>{j===1&&<small>{x.toLowerCase().replace(" ",".")}@email.com<br/>(561) 555-01{i+20}</small>}</span>)}<button>•••</button></div>)}</div><footer className="features">◆ Double-booking protection　◆ Weighted host routing　◆ Resource locking　◆ Automated reminders　◆ Calendar sync ready</footer></section>}
